import * as fs from 'fs/promises';
import * as path from 'path';

export class UnityTool {
  public async injectCode(filePath: string, code: string): Promise<void> {
    const fullPath = path.resolve(process.cwd(), '../Assets/Scripts', filePath);
    console.log(`Injecting code into ${fullPath}`);
    await fs.writeFile(fullPath, code);
  }

  public async generateComponent(name: string, namespace: string = "MilehighWorld.Core"): Promise<string> {
    return `using UnityEngine;

namespace ${namespace}
{
    public class ${name} : MonoBehaviour
    {
        void Awake()
        {
            // Generated by OpenClaw
        }
    }
}`;
  }
}
